name: Update Profile README

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Profil README Repoyu Klonla
        uses: actions/checkout@v2

      - name: Gizli Mesaj Ekle
        run: |
          echo "ekle." >> README.md
          git config --global user.email "tunabusiness25@gmail.com"
          git config --global user.name "tunadeveloper"
          git add README.md
          git commit -m "Profil README Güncellendi"
          git push
